// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: tdf_note/v1/tdf_note.proto

package tdf_notev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TdfNoteService_CreateTdfNote_FullMethodName  = "/tdf_notes.v1.TdfNoteService/CreateTdfNote"
	TdfNoteService_GetTdfNote_FullMethodName     = "/tdf_notes.v1.TdfNoteService/GetTdfNote"
	TdfNoteService_QueryTdfNotes_FullMethodName  = "/tdf_notes.v1.TdfNoteService/QueryTdfNotes"
	TdfNoteService_StreamTdfNotes_FullMethodName = "/tdf_notes.v1.TdfNoteService/StreamTdfNotes"
)

// TdfNoteServiceClient is the client API for TdfNoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TdfNoteServiceClient interface {
	// RPC for creating a new TDF note
	CreateTdfNote(ctx context.Context, in *CreateTdfNoteRequest, opts ...grpc.CallOption) (*CreateTdfNoteResponse, error)
	// RPC for retrieving a TDF note by ID
	GetTdfNote(ctx context.Context, in *GetTdfNoteRequest, opts ...grpc.CallOption) (*GetTdfNoteResponse, error)
	// RPC for querying notes associated with a TDF object
	QueryTdfNotes(ctx context.Context, in *QueryTdfNotesRequest, opts ...grpc.CallOption) (*QueryTdfNotesResponse, error)
	// RPC for streaming TDF notes (e.g., for real-time updates)
	StreamTdfNotes(ctx context.Context, in *StreamTdfNotesRequest, opts ...grpc.CallOption) (TdfNoteService_StreamTdfNotesClient, error)
}

type tdfNoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTdfNoteServiceClient(cc grpc.ClientConnInterface) TdfNoteServiceClient {
	return &tdfNoteServiceClient{cc}
}

func (c *tdfNoteServiceClient) CreateTdfNote(ctx context.Context, in *CreateTdfNoteRequest, opts ...grpc.CallOption) (*CreateTdfNoteResponse, error) {
	out := new(CreateTdfNoteResponse)
	err := c.cc.Invoke(ctx, TdfNoteService_CreateTdfNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tdfNoteServiceClient) GetTdfNote(ctx context.Context, in *GetTdfNoteRequest, opts ...grpc.CallOption) (*GetTdfNoteResponse, error) {
	out := new(GetTdfNoteResponse)
	err := c.cc.Invoke(ctx, TdfNoteService_GetTdfNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tdfNoteServiceClient) QueryTdfNotes(ctx context.Context, in *QueryTdfNotesRequest, opts ...grpc.CallOption) (*QueryTdfNotesResponse, error) {
	out := new(QueryTdfNotesResponse)
	err := c.cc.Invoke(ctx, TdfNoteService_QueryTdfNotes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tdfNoteServiceClient) StreamTdfNotes(ctx context.Context, in *StreamTdfNotesRequest, opts ...grpc.CallOption) (TdfNoteService_StreamTdfNotesClient, error) {
	stream, err := c.cc.NewStream(ctx, &TdfNoteService_ServiceDesc.Streams[0], TdfNoteService_StreamTdfNotes_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &tdfNoteServiceStreamTdfNotesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TdfNoteService_StreamTdfNotesClient interface {
	Recv() (*StreamTdfNotesResponse, error)
	grpc.ClientStream
}

type tdfNoteServiceStreamTdfNotesClient struct {
	grpc.ClientStream
}

func (x *tdfNoteServiceStreamTdfNotesClient) Recv() (*StreamTdfNotesResponse, error) {
	m := new(StreamTdfNotesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TdfNoteServiceServer is the server API for TdfNoteService service.
// All implementations must embed UnimplementedTdfNoteServiceServer
// for forward compatibility
type TdfNoteServiceServer interface {
	// RPC for creating a new TDF note
	CreateTdfNote(context.Context, *CreateTdfNoteRequest) (*CreateTdfNoteResponse, error)
	// RPC for retrieving a TDF note by ID
	GetTdfNote(context.Context, *GetTdfNoteRequest) (*GetTdfNoteResponse, error)
	// RPC for querying notes associated with a TDF object
	QueryTdfNotes(context.Context, *QueryTdfNotesRequest) (*QueryTdfNotesResponse, error)
	// RPC for streaming TDF notes (e.g., for real-time updates)
	StreamTdfNotes(*StreamTdfNotesRequest, TdfNoteService_StreamTdfNotesServer) error
	mustEmbedUnimplementedTdfNoteServiceServer()
}

// UnimplementedTdfNoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTdfNoteServiceServer struct {
}

func (UnimplementedTdfNoteServiceServer) CreateTdfNote(context.Context, *CreateTdfNoteRequest) (*CreateTdfNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTdfNote not implemented")
}
func (UnimplementedTdfNoteServiceServer) GetTdfNote(context.Context, *GetTdfNoteRequest) (*GetTdfNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTdfNote not implemented")
}
func (UnimplementedTdfNoteServiceServer) QueryTdfNotes(context.Context, *QueryTdfNotesRequest) (*QueryTdfNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTdfNotes not implemented")
}
func (UnimplementedTdfNoteServiceServer) StreamTdfNotes(*StreamTdfNotesRequest, TdfNoteService_StreamTdfNotesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTdfNotes not implemented")
}
func (UnimplementedTdfNoteServiceServer) mustEmbedUnimplementedTdfNoteServiceServer() {}

// UnsafeTdfNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TdfNoteServiceServer will
// result in compilation errors.
type UnsafeTdfNoteServiceServer interface {
	mustEmbedUnimplementedTdfNoteServiceServer()
}

func RegisterTdfNoteServiceServer(s grpc.ServiceRegistrar, srv TdfNoteServiceServer) {
	s.RegisterService(&TdfNoteService_ServiceDesc, srv)
}

func _TdfNoteService_CreateTdfNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTdfNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TdfNoteServiceServer).CreateTdfNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TdfNoteService_CreateTdfNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TdfNoteServiceServer).CreateTdfNote(ctx, req.(*CreateTdfNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TdfNoteService_GetTdfNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTdfNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TdfNoteServiceServer).GetTdfNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TdfNoteService_GetTdfNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TdfNoteServiceServer).GetTdfNote(ctx, req.(*GetTdfNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TdfNoteService_QueryTdfNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTdfNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TdfNoteServiceServer).QueryTdfNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TdfNoteService_QueryTdfNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TdfNoteServiceServer).QueryTdfNotes(ctx, req.(*QueryTdfNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TdfNoteService_StreamTdfNotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTdfNotesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TdfNoteServiceServer).StreamTdfNotes(m, &tdfNoteServiceStreamTdfNotesServer{stream})
}

type TdfNoteService_StreamTdfNotesServer interface {
	Send(*StreamTdfNotesResponse) error
	grpc.ServerStream
}

type tdfNoteServiceStreamTdfNotesServer struct {
	grpc.ServerStream
}

func (x *tdfNoteServiceStreamTdfNotesServer) Send(m *StreamTdfNotesResponse) error {
	return x.ServerStream.SendMsg(m)
}

// TdfNoteService_ServiceDesc is the grpc.ServiceDesc for TdfNoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TdfNoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tdf_notes.v1.TdfNoteService",
	HandlerType: (*TdfNoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTdfNote",
			Handler:    _TdfNoteService_CreateTdfNote_Handler,
		},
		{
			MethodName: "GetTdfNote",
			Handler:    _TdfNoteService_GetTdfNote_Handler,
		},
		{
			MethodName: "QueryTdfNotes",
			Handler:    _TdfNoteService_QueryTdfNotes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTdfNotes",
			Handler:       _TdfNoteService_StreamTdfNotes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tdf_note/v1/tdf_note.proto",
}
