#!/bin/bash

set -e
export PGUSER="$POSTGRES_USER"
psql -d $POSTGRES_DB << EOSQL
CREATE TABLE tdf_stream (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  src_type TEXT NOT NULL,
  geo GEOMETRY NULL,
  search JSONB NULL,
  tdf_blob BYTEA NULL,
  tdf_uri TEXT NULL
);

COMMENT ON TABLE tdf_stream IS 'stream of tdf data';
COMMENT ON COLUMN tdf_stream.id IS 'uuid primary key generated by the database';
COMMENT ON COLUMN tdf_stream.ts IS 'timestamp generated by the database';
COMMENT ON COLUMN tdf_stream.src_type IS 'source type of the data';
COMMENT ON COLUMN tdf_stream.geo IS 'geospatial data';
COMMENT ON COLUMN tdf_stream.search IS 'plaintext json search index';
COMMENT ON COLUMN tdf_stream.tdf_blob IS 'tdf data blob';
COMMENT ON COLUMN tdf_stream.tdf_uri IS 'tdf data uri';
EOSQL