// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file tdf_object/v1/tdf_object.proto (package tdf_object.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTdfObjectRequest, CreateTdfObjectResponse, GetEntitlementsRequest, GetEntitlementsResponse, GetSrcTypeRequest, GetSrcTypeResponse, GetTdfObjectRequest, GetTdfObjectResponse, ListSrcTypesRequest, ListSrcTypesResponse, QueryTdfObjectsRequest, QueryTdfObjectsResponse, StreamTdfObjectsRequest, StreamTdfObjectsResponse } from "./tdf_object_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service tdf_object.v1.TdfObjectService
 */
export const TdfObjectService = {
  typeName: "tdf_object.v1.TdfObjectService",
  methods: {
    /**
     * @generated from rpc tdf_object.v1.TdfObjectService.CreateTdfObject
     */
    createTdfObject: {
      name: "CreateTdfObject",
      I: CreateTdfObjectRequest,
      O: CreateTdfObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tdf_object.v1.TdfObjectService.GetTdfObject
     */
    getTdfObject: {
      name: "GetTdfObject",
      I: GetTdfObjectRequest,
      O: GetTdfObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tdf_object.v1.TdfObjectService.QueryTdfObjects
     */
    queryTdfObjects: {
      name: "QueryTdfObjects",
      I: QueryTdfObjectsRequest,
      O: QueryTdfObjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tdf_object.v1.TdfObjectService.StreamTdfObjects
     */
    streamTdfObjects: {
      name: "StreamTdfObjects",
      I: StreamTdfObjectsRequest,
      O: StreamTdfObjectsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc tdf_object.v1.TdfObjectService.GetSrcType
     */
    getSrcType: {
      name: "GetSrcType",
      I: GetSrcTypeRequest,
      O: GetSrcTypeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tdf_object.v1.TdfObjectService.ListSrcTypes
     */
    listSrcTypes: {
      name: "ListSrcTypes",
      I: ListSrcTypesRequest,
      O: ListSrcTypesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tdf_object.v1.TdfObjectService.GetEntitlements
     */
    getEntitlements: {
      name: "GetEntitlements",
      I: GetEntitlementsRequest,
      O: GetEntitlementsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

