// @generated by protoc-gen-es v1.9.0 with parameter "target=ts,import_extension=none"
// @generated from file tdf_object/v1/tdf_note.proto (package tdf_notes.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * The StreamEventType enum is reused from the previous schema
 *
 * @generated from enum tdf_notes.v1.StreamEventType
 */
export enum StreamEventType {
  /**
   * @generated from enum value: STREAM_EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * system events
   *
   * @generated from enum value: STREAM_EVENT_TYPE_STARTUP = 1;
   */
  STARTUP = 1,

  /**
   * @generated from enum value: STREAM_EVENT_TYPE_SHUTDOWN = 2;
   */
  SHUTDOWN = 2,

  /**
   * @generated from enum value: STREAM_EVENT_TYPE_RESTART = 3;
   */
  RESTART = 3,

  /**
   * @generated from enum value: STREAM_EVENT_TYPE_MAINTENANCE = 4;
   */
  MAINTENANCE = 4,

  /**
   * data events
   *
   * @generated from enum value: STREAM_EVENT_TYPE_CONNECTED = 5;
   */
  CONNECTED = 5,

  /**
   * @generated from enum value: STREAM_EVENT_TYPE_HEARTBEAT = 6;
   */
  HEARTBEAT = 6,

  /**
   * generic events
   *
   * @generated from enum value: STREAM_EVENT_TYPE_GENERIC_ERROR = 10;
   */
  GENERIC_ERROR = 10,

  /**
   * @generated from enum value: STREAM_EVENT_TYPE_SERVER_ERROR = 11;
   */
  SERVER_ERROR = 11,

  /**
   * @generated from enum value: STREAM_EVENT_TYPE_DATA_ERROR = 12;
   */
  DATA_ERROR = 12,

  /**
   * tdf_notes stream events
   *
   * @generated from enum value: STREAM_EVENT_TYPE_TDF_NOTES_NEW = 20;
   */
  TDF_NOTES_NEW = 20,
}
// Retrieve enum metadata with: proto3.getEnumType(StreamEventType)
proto3.util.setEnumType(StreamEventType, "tdf_notes.v1.StreamEventType", [
  { no: 0, name: "STREAM_EVENT_TYPE_UNSPECIFIED" },
  { no: 1, name: "STREAM_EVENT_TYPE_STARTUP" },
  { no: 2, name: "STREAM_EVENT_TYPE_SHUTDOWN" },
  { no: 3, name: "STREAM_EVENT_TYPE_RESTART" },
  { no: 4, name: "STREAM_EVENT_TYPE_MAINTENANCE" },
  { no: 5, name: "STREAM_EVENT_TYPE_CONNECTED" },
  { no: 6, name: "STREAM_EVENT_TYPE_HEARTBEAT" },
  { no: 10, name: "STREAM_EVENT_TYPE_GENERIC_ERROR" },
  { no: 11, name: "STREAM_EVENT_TYPE_SERVER_ERROR" },
  { no: 12, name: "STREAM_EVENT_TYPE_DATA_ERROR" },
  { no: 20, name: "STREAM_EVENT_TYPE_TDF_NOTES_NEW" },
]);

/**
 * Represents a note associated with a TDF object
 *
 * @generated from message tdf_notes.v1.TdfNote
 */
export class TdfNote extends Message<TdfNote> {
  /**
   * Unique identifier for the note
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Timestamp of the note creation
   *
   * @generated from field: google.protobuf.Timestamp ts = 2;
   */
  ts?: Timestamp;

  /**
   * Parent TDF object ID (foreign key to tdf_objects)
   *
   * @generated from field: string parent_id = 3;
   */
  parentId = "";

  /**
   * Plaintext JSON search index for searching notes
   *
   * @generated from field: string search = 4;
   */
  search = "";

  /**
   * Binary TDF data for the note
   *
   * @generated from field: bytes tdf_blob = 5;
   */
  tdfBlob = new Uint8Array(0);

  /**
   * URI pointing to the note data
   *
   * @generated from field: string tdf_uri = 6;
   */
  tdfUri = "";

  /**
   * Timestamp of when the note was created
   *
   * @generated from field: google.protobuf.Timestamp _created_at = 7;
   */
  CreatedAt?: Timestamp;

  /**
   * Who created the note
   *
   * @generated from field: string _created_by = 8;
   */
  CreatedBy = "";

  constructor(data?: PartialMessage<TdfNote>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tdf_notes.v1.TdfNote";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ts", kind: "message", T: Timestamp },
    { no: 3, name: "parent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "search", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "tdf_blob", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 6, name: "tdf_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "_created_at", kind: "message", T: Timestamp },
    { no: 8, name: "_created_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TdfNote {
    return new TdfNote().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TdfNote {
    return new TdfNote().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TdfNote {
    return new TdfNote().fromJsonString(jsonString, options);
  }

  static equals(a: TdfNote | PlainMessage<TdfNote> | undefined, b: TdfNote | PlainMessage<TdfNote> | undefined): boolean {
    return proto3.util.equals(TdfNote, a, b);
  }
}

/**
 * Request message for creating a new note
 *
 * @generated from message tdf_notes.v1.CreateTdfNoteRequest
 */
export class CreateTdfNoteRequest extends Message<CreateTdfNoteRequest> {
  /**
   * Parent TDF object ID (foreign key to tdf_objects)
   *
   * @generated from field: string parent_id = 1;
   */
  parentId = "";

  /**
   * Plaintext JSON search index for searching notes
   *
   * @generated from field: string search = 2;
   */
  search = "";

  /**
   * Binary TDF data for the note
   *
   * @generated from field: bytes tdf_blob = 3;
   */
  tdfBlob = new Uint8Array(0);

  /**
   * URI pointing to the note data
   *
   * @generated from field: string tdf_uri = 4;
   */
  tdfUri = "";

  /**
   * Timestamp of the note
   *
   * @generated from field: google.protobuf.Timestamp ts = 5;
   */
  ts?: Timestamp;

  constructor(data?: PartialMessage<CreateTdfNoteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tdf_notes.v1.CreateTdfNoteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "parent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "search", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tdf_blob", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "tdf_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "ts", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateTdfNoteRequest {
    return new CreateTdfNoteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateTdfNoteRequest {
    return new CreateTdfNoteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateTdfNoteRequest {
    return new CreateTdfNoteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateTdfNoteRequest | PlainMessage<CreateTdfNoteRequest> | undefined, b: CreateTdfNoteRequest | PlainMessage<CreateTdfNoteRequest> | undefined): boolean {
    return proto3.util.equals(CreateTdfNoteRequest, a, b);
  }
}

/**
 * Response message for creating a new note
 *
 * @generated from message tdf_notes.v1.CreateTdfNoteResponse
 */
export class CreateTdfNoteResponse extends Message<CreateTdfNoteResponse> {
  /**
   * Unique identifier of the newly created note
   *
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<CreateTdfNoteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tdf_notes.v1.CreateTdfNoteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateTdfNoteResponse {
    return new CreateTdfNoteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateTdfNoteResponse {
    return new CreateTdfNoteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateTdfNoteResponse {
    return new CreateTdfNoteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateTdfNoteResponse | PlainMessage<CreateTdfNoteResponse> | undefined, b: CreateTdfNoteResponse | PlainMessage<CreateTdfNoteResponse> | undefined): boolean {
    return proto3.util.equals(CreateTdfNoteResponse, a, b);
  }
}

/**
 * Request message to retrieve a note by ID
 *
 * @generated from message tdf_notes.v1.GetTdfNoteRequest
 */
export class GetTdfNoteRequest extends Message<GetTdfNoteRequest> {
  /**
   * The ID of the note to retrieve
   *
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetTdfNoteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tdf_notes.v1.GetTdfNoteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTdfNoteRequest {
    return new GetTdfNoteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTdfNoteRequest {
    return new GetTdfNoteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTdfNoteRequest {
    return new GetTdfNoteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetTdfNoteRequest | PlainMessage<GetTdfNoteRequest> | undefined, b: GetTdfNoteRequest | PlainMessage<GetTdfNoteRequest> | undefined): boolean {
    return proto3.util.equals(GetTdfNoteRequest, a, b);
  }
}

/**
 * Response message for retrieving a note by ID
 *
 * @generated from message tdf_notes.v1.GetTdfNoteResponse
 */
export class GetTdfNoteResponse extends Message<GetTdfNoteResponse> {
  /**
   * The note object
   *
   * @generated from field: tdf_notes.v1.TdfNote tdf_note = 1;
   */
  tdfNote?: TdfNote;

  constructor(data?: PartialMessage<GetTdfNoteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tdf_notes.v1.GetTdfNoteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tdf_note", kind: "message", T: TdfNote },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTdfNoteResponse {
    return new GetTdfNoteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTdfNoteResponse {
    return new GetTdfNoteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTdfNoteResponse {
    return new GetTdfNoteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetTdfNoteResponse | PlainMessage<GetTdfNoteResponse> | undefined, b: GetTdfNoteResponse | PlainMessage<GetTdfNoteResponse> | undefined): boolean {
    return proto3.util.equals(GetTdfNoteResponse, a, b);
  }
}

/**
 * Request message for querying notes associated with a TDF object
 *
 * @generated from message tdf_notes.v1.QueryTdfNotesRequest
 */
export class QueryTdfNotesRequest extends Message<QueryTdfNotesRequest> {
  /**
   * Parent TDF object ID (foreign key to tdf_objects)
   *
   * @generated from field: string parent_id = 1;
   */
  parentId = "";

  /**
   * Start timestamp for querying notes
   *
   * @generated from field: google.protobuf.Timestamp start_ts = 2;
   */
  startTs?: Timestamp;

  /**
   * End timestamp for querying notes
   *
   * @generated from field: google.protobuf.Timestamp end_ts = 3;
   */
  endTs?: Timestamp;

  /**
   * Search query for filtering notes
   *
   * @generated from field: string search = 4;
   */
  search = "";

  constructor(data?: PartialMessage<QueryTdfNotesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tdf_notes.v1.QueryTdfNotesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "parent_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "start_ts", kind: "message", T: Timestamp },
    { no: 3, name: "end_ts", kind: "message", T: Timestamp },
    { no: 4, name: "search", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTdfNotesRequest {
    return new QueryTdfNotesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTdfNotesRequest {
    return new QueryTdfNotesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTdfNotesRequest {
    return new QueryTdfNotesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryTdfNotesRequest | PlainMessage<QueryTdfNotesRequest> | undefined, b: QueryTdfNotesRequest | PlainMessage<QueryTdfNotesRequest> | undefined): boolean {
    return proto3.util.equals(QueryTdfNotesRequest, a, b);
  }
}

/**
 * Response message for querying notes associated with a TDF object
 *
 * @generated from message tdf_notes.v1.QueryTdfNotesResponse
 */
export class QueryTdfNotesResponse extends Message<QueryTdfNotesResponse> {
  /**
   * List of notes associated with the parent TDF object
   *
   * @generated from field: repeated tdf_notes.v1.TdfNote tdf_notes = 1;
   */
  tdfNotes: TdfNote[] = [];

  constructor(data?: PartialMessage<QueryTdfNotesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tdf_notes.v1.QueryTdfNotesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tdf_notes", kind: "message", T: TdfNote, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTdfNotesResponse {
    return new QueryTdfNotesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTdfNotesResponse {
    return new QueryTdfNotesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTdfNotesResponse {
    return new QueryTdfNotesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryTdfNotesResponse | PlainMessage<QueryTdfNotesResponse> | undefined, b: QueryTdfNotesResponse | PlainMessage<QueryTdfNotesResponse> | undefined): boolean {
    return proto3.util.equals(QueryTdfNotesResponse, a, b);
  }
}

/**
 * todo: intentionally left empty until we decide if any filtering needs to be done
 *
 * @generated from message tdf_notes.v1.StreamTdfNotesRequest
 */
export class StreamTdfNotesRequest extends Message<StreamTdfNotesRequest> {
  constructor(data?: PartialMessage<StreamTdfNotesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tdf_notes.v1.StreamTdfNotesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamTdfNotesRequest {
    return new StreamTdfNotesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamTdfNotesRequest {
    return new StreamTdfNotesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamTdfNotesRequest {
    return new StreamTdfNotesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StreamTdfNotesRequest | PlainMessage<StreamTdfNotesRequest> | undefined, b: StreamTdfNotesRequest | PlainMessage<StreamTdfNotesRequest> | undefined): boolean {
    return proto3.util.equals(StreamTdfNotesRequest, a, b);
  }
}

/**
 * Stream response for streaming note events (similar to streaming TDF objects)
 *
 * @generated from message tdf_notes.v1.StreamTdfNotesResponse
 */
export class StreamTdfNotesResponse extends Message<StreamTdfNotesResponse> {
  /**
   * Type of stream event (e.g., new note)
   *
   * @generated from field: tdf_notes.v1.StreamEventType event_type = 1;
   */
  eventType = StreamEventType.UNSPECIFIED;

  /**
   * Details about the event
   *
   * @generated from field: string event_detail = 2;
   */
  eventDetail = "";

  /**
   * List of notes being streamed
   *
   * @generated from field: repeated tdf_notes.v1.TdfNote tdf_notes = 6;
   */
  tdfNotes: TdfNote[] = [];

  constructor(data?: PartialMessage<StreamTdfNotesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "tdf_notes.v1.StreamTdfNotesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_type", kind: "enum", T: proto3.getEnumType(StreamEventType) },
    { no: 2, name: "event_detail", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "tdf_notes", kind: "message", T: TdfNote, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamTdfNotesResponse {
    return new StreamTdfNotesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamTdfNotesResponse {
    return new StreamTdfNotesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamTdfNotesResponse {
    return new StreamTdfNotesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StreamTdfNotesResponse | PlainMessage<StreamTdfNotesResponse> | undefined, b: StreamTdfNotesResponse | PlainMessage<StreamTdfNotesResponse> | undefined): boolean {
    return proto3.util.equals(StreamTdfNotesResponse, a, b);
  }
}

