// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file tdf_object/v1/tdf_note.proto (package tdf_notes.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTdfNoteRequest, CreateTdfNoteResponse, GetTdfNoteRequest, GetTdfNoteResponse, QueryTdfNotesRequest, QueryTdfNotesResponse, StreamTdfNotesRequest, StreamTdfNotesResponse } from "./tdf_note_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definition for handling TDF notes
 *
 * @generated from service tdf_notes.v1.TdfNoteService
 */
export const TdfNoteService = {
  typeName: "tdf_notes.v1.TdfNoteService",
  methods: {
    /**
     * RPC for creating a new TDF note
     *
     * @generated from rpc tdf_notes.v1.TdfNoteService.CreateTdfNote
     */
    createTdfNote: {
      name: "CreateTdfNote",
      I: CreateTdfNoteRequest,
      O: CreateTdfNoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * RPC for retrieving a TDF note by ID
     *
     * @generated from rpc tdf_notes.v1.TdfNoteService.GetTdfNote
     */
    getTdfNote: {
      name: "GetTdfNote",
      I: GetTdfNoteRequest,
      O: GetTdfNoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * RPC for querying notes associated with a TDF object
     *
     * @generated from rpc tdf_notes.v1.TdfNoteService.QueryTdfNotes
     */
    queryTdfNotes: {
      name: "QueryTdfNotes",
      I: QueryTdfNotesRequest,
      O: QueryTdfNotesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * RPC for streaming TDF notes (e.g., for real-time updates)
     *
     * @generated from rpc tdf_notes.v1.TdfNoteService.StreamTdfNotes
     */
    streamTdfNotes: {
      name: "StreamTdfNotes",
      I: StreamTdfNotesRequest,
      O: StreamTdfNotesResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

