name: Container Security Check

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

permissions: read-all

jobs:
  container-security-check:
    uses: virtru-corp/.github/.github/workflows/container-security-check.yaml@v1
    with: 
      dockerfile: 'cop.Dockerfile'