apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f ./docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: cop
  name: cop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cop
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f ./docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: cop
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: TARGETARCH
              value: amd64
            - name: TARGETOS
              value: linux
          image: {{ .Values.cop.image.repo }}/{{ .Values.cop.image.name }}:{{ .Values.cop.image.tag }}
          name: cop
          ports:
            - containerPort: 5001
              protocol: TCP
            - containerPort: 5002
              protocol: TCP
          volumeMounts:
            - name: cop-config
              mountPath: /etc/dsp-cop/config.yaml
              subPath: config.yaml
            - name: cop-certs
              mountPath: /app/dsp-keys
            - name: cop-trust
              mountPath: /etc/ssl/certs
      restartPolicy: Always
      volumes:
        - name: cop-config
          configMap:
            name: cop-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: cop-certs
          secret:
            secretName: {{ .Values.dsp_cert_secret }}
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        - name: cop-trust
          secret:
            secretName: {{ .Values.dsp_cert_secret }}
            items:
              - key: ca.crt
                path: ca-certificates.crt