services:

  cop-db:
    extends:
      file: ./docker-compose.cop-db.yaml
      service: cop-db

  tagging:
    extends:
      file: ./docker-compose.tagging.yaml
      service: tagging
  
#================================================================
# Start NiFi
#----------------------------------------------------------------
  nifi:
    image: ${NIFI_IMAGE:-ghcr.io/ttschampel/nifi/nifi-1.25.0-jre17:latest}
    depends_on:
      cop-db:
        condition: service_healthy
        restart: true
    restart: always
    ulimits:
      nofile:
        soft: 2048
        hard: 4096
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTP_HOST=0.0.0.0
      - TDF_FLOW_TAGGING_AUTH=false
      - TDF_FLOW_TAGGING_USE_SSL=false
      - TDF_FLOW_TAGGING_ENDPOINT=${TAGGING_PDP_ENDPOINT}
      - TDFDB_DATABASE_USERNAME=${DB_USERNAME}
      - TDFDB_DATABASE_PASSWORD=${DB_PASSWORD}
      - TDFDB_DATABASE_CATALOG_NAME=postgres
      - TDFDB_DATABASE_SCHEMA_NAME=public
      - TDFDB_DATABASE_HOST=cop-db
      - TDFDB_DATABASE_NAME=${DB_NAME}
      - TDFDB_DATABASE_TABLE=${DB_TABLENAME}
      - TDF_FLOW_PLATFORM_ENDPOINT=${PLATFORM_ENDPOINT}
      - TDF_FLOW_NANO_KAS_URL=${KAS_NANO_URL}
      - TDF_FLOW_TDF_KAS_URL=${KAS_TDF_URL}
      - TDF_FLOW_CLIENT_ID=${NIFI_CLIENT_ID}
      - TDF_FLOW_CLIENT_SECRET=${NIFI_CLIENT_SECRET}
      - TDF_TRUSTSTORE_FILENAME=/opt/nifi/nifi-current/truststore/ca.jks
    volumes:
      - ../nifi/extensions:/opt/nifi/nifi-current/extensions #mount custom NARs
      - ../truststore:/opt/nifi/nifi-current/truststore # mounts truststore
      - ../nifi/custom-libs:/opt/nifi/nifi-current/custom-libs #mount additional libs
      - ../nifi/sample_data:/opt/nifi/nifi-current/sample_data #mount sample data
    ports:
      - 18080:8080/tcp
    extra_hosts:
      - "local-dsp.virtru.com:172.17.0.1" #host and ip