{{ if .Values.nifi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cop-nifi
  #annotations:
  labels:
    app: nifi
spec:
  type: ClusterIP
  ports:
    - name: "443"
      port: 443
      targetPort: 8080
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    app: nifi
{{ end }}
