// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	geos "github.com/twpayne/go-geos"
)

type SrcType struct {
	ID         string `json:"id"`
	FormSchema []byte `json:"form_schema"`
	UiSchema   []byte `json:"ui_schema"`
	Metadata   []byte `json:"metadata"`
}

// stream of tdf data
type TdfObject struct {
	// uuid primary key generated by the database
	ID uuid.UUID `json:"id"`
	// timestamp generated by the database
	Ts pgtype.Timestamp `json:"ts"`
	// source type of the data
	SrcType string `json:"src_type"`
	// geospatial data
	Geo *geos.Geom `json:"geo"`
	// plaintext json search index
	Search []byte `json:"search"`
	// tdf data blob
	TdfBlob []byte `json:"tdf_blob"`
	// tdf data uri
	TdfUri    pgtype.Text      `json:"tdf_uri"`
	CreatedAt pgtype.Timestamp `json:"_created_at"`
	CreatedBy pgtype.Text      `json:"_created_by"`
}
