// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tdf_note/v1/tdf_note.proto

package tdf_notev1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	v1 "github.com/virtru-corp/dsp-cop/api/proto/github.com/virtru-corp/dsp-cop/api/proto/tdf_note/v1"

	connect "connectrpc.com/connect"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TdfNoteServiceName is the fully-qualified name of the TdfNoteService service.
	TdfNoteServiceName = "tdf_notes.v1.TdfNoteService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TdfNoteServiceCreateTdfNoteProcedure is the fully-qualified name of the TdfNoteService's
	// CreateTdfNote RPC.
	TdfNoteServiceCreateTdfNoteProcedure = "/tdf_notes.v1.TdfNoteService/CreateTdfNote"
	// TdfNoteServiceGetTdfNoteProcedure is the fully-qualified name of the TdfNoteService's GetTdfNote
	// RPC.
	TdfNoteServiceGetTdfNoteProcedure = "/tdf_notes.v1.TdfNoteService/GetTdfNote"
	// TdfNoteServiceQueryTdfNotesProcedure is the fully-qualified name of the TdfNoteService's
	// QueryTdfNotes RPC.
	TdfNoteServiceQueryTdfNotesProcedure = "/tdf_notes.v1.TdfNoteService/QueryTdfNotes"
	// TdfNoteServiceStreamTdfNotesProcedure is the fully-qualified name of the TdfNoteService's
	// StreamTdfNotes RPC.
	TdfNoteServiceStreamTdfNotesProcedure = "/tdf_notes.v1.TdfNoteService/StreamTdfNotes"
)

// TdfNoteServiceClient is a client for the tdf_notes.v1.TdfNoteService service.
type TdfNoteServiceClient interface {
	// RPC for creating a new TDF note
	CreateTdfNote(context.Context, *connect.Request[v1.CreateTdfNoteRequest]) (*connect.Response[v1.CreateTdfNoteResponse], error)
	// RPC for retrieving a TDF note by ID
	GetTdfNote(context.Context, *connect.Request[v1.GetTdfNoteRequest]) (*connect.Response[v1.GetTdfNoteResponse], error)
	// RPC for querying notes associated with a TDF object
	QueryTdfNotes(context.Context, *connect.Request[v1.QueryTdfNotesRequest]) (*connect.Response[v1.QueryTdfNotesResponse], error)
	// RPC for streaming TDF notes (e.g., for real-time updates)
	StreamTdfNotes(context.Context, *connect.Request[v1.StreamTdfNotesRequest]) (*connect.ServerStreamForClient[v1.StreamTdfNotesResponse], error)
}

// NewTdfNoteServiceClient constructs a client for the tdf_notes.v1.TdfNoteService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTdfNoteServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TdfNoteServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tdfNoteServiceMethods := v1.File_tdf_note_v1_tdf_note_proto.Services().ByName("TdfNoteService").Methods()
	return &tdfNoteServiceClient{
		createTdfNote: connect.NewClient[v1.CreateTdfNoteRequest, v1.CreateTdfNoteResponse](
			httpClient,
			baseURL+TdfNoteServiceCreateTdfNoteProcedure,
			connect.WithSchema(tdfNoteServiceMethods.ByName("CreateTdfNote")),
			connect.WithClientOptions(opts...),
		),
		getTdfNote: connect.NewClient[v1.GetTdfNoteRequest, v1.GetTdfNoteResponse](
			httpClient,
			baseURL+TdfNoteServiceGetTdfNoteProcedure,
			connect.WithSchema(tdfNoteServiceMethods.ByName("GetTdfNote")),
			connect.WithClientOptions(opts...),
		),
		queryTdfNotes: connect.NewClient[v1.QueryTdfNotesRequest, v1.QueryTdfNotesResponse](
			httpClient,
			baseURL+TdfNoteServiceQueryTdfNotesProcedure,
			connect.WithSchema(tdfNoteServiceMethods.ByName("QueryTdfNotes")),
			connect.WithClientOptions(opts...),
		),
		streamTdfNotes: connect.NewClient[v1.StreamTdfNotesRequest, v1.StreamTdfNotesResponse](
			httpClient,
			baseURL+TdfNoteServiceStreamTdfNotesProcedure,
			connect.WithSchema(tdfNoteServiceMethods.ByName("StreamTdfNotes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tdfNoteServiceClient implements TdfNoteServiceClient.
type tdfNoteServiceClient struct {
	createTdfNote  *connect.Client[v1.CreateTdfNoteRequest, v1.CreateTdfNoteResponse]
	getTdfNote     *connect.Client[v1.GetTdfNoteRequest, v1.GetTdfNoteResponse]
	queryTdfNotes  *connect.Client[v1.QueryTdfNotesRequest, v1.QueryTdfNotesResponse]
	streamTdfNotes *connect.Client[v1.StreamTdfNotesRequest, v1.StreamTdfNotesResponse]
}

// CreateTdfNote calls tdf_notes.v1.TdfNoteService.CreateTdfNote.
func (c *tdfNoteServiceClient) CreateTdfNote(ctx context.Context, req *connect.Request[v1.CreateTdfNoteRequest]) (*connect.Response[v1.CreateTdfNoteResponse], error) {
	return c.createTdfNote.CallUnary(ctx, req)
}

// GetTdfNote calls tdf_notes.v1.TdfNoteService.GetTdfNote.
func (c *tdfNoteServiceClient) GetTdfNote(ctx context.Context, req *connect.Request[v1.GetTdfNoteRequest]) (*connect.Response[v1.GetTdfNoteResponse], error) {
	return c.getTdfNote.CallUnary(ctx, req)
}

// QueryTdfNotes calls tdf_notes.v1.TdfNoteService.QueryTdfNotes.
func (c *tdfNoteServiceClient) QueryTdfNotes(ctx context.Context, req *connect.Request[v1.QueryTdfNotesRequest]) (*connect.Response[v1.QueryTdfNotesResponse], error) {
	return c.queryTdfNotes.CallUnary(ctx, req)
}

// StreamTdfNotes calls tdf_notes.v1.TdfNoteService.StreamTdfNotes.
func (c *tdfNoteServiceClient) StreamTdfNotes(ctx context.Context, req *connect.Request[v1.StreamTdfNotesRequest]) (*connect.ServerStreamForClient[v1.StreamTdfNotesResponse], error) {
	return c.streamTdfNotes.CallServerStream(ctx, req)
}

// TdfNoteServiceHandler is an implementation of the tdf_notes.v1.TdfNoteService service.
type TdfNoteServiceHandler interface {
	// RPC for creating a new TDF note
	CreateTdfNote(context.Context, *connect.Request[v1.CreateTdfNoteRequest]) (*connect.Response[v1.CreateTdfNoteResponse], error)
	// RPC for retrieving a TDF note by ID
	GetTdfNote(context.Context, *connect.Request[v1.GetTdfNoteRequest]) (*connect.Response[v1.GetTdfNoteResponse], error)
	// RPC for querying notes associated with a TDF object
	QueryTdfNotes(context.Context, *connect.Request[v1.QueryTdfNotesRequest]) (*connect.Response[v1.QueryTdfNotesResponse], error)
	// RPC for streaming TDF notes (e.g., for real-time updates)
	StreamTdfNotes(context.Context, *connect.Request[v1.StreamTdfNotesRequest], *connect.ServerStream[v1.StreamTdfNotesResponse]) error
}

// NewTdfNoteServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTdfNoteServiceHandler(svc TdfNoteServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tdfNoteServiceMethods := v1.File_tdf_note_v1_tdf_note_proto.Services().ByName("TdfNoteService").Methods()
	tdfNoteServiceCreateTdfNoteHandler := connect.NewUnaryHandler(
		TdfNoteServiceCreateTdfNoteProcedure,
		svc.CreateTdfNote,
		connect.WithSchema(tdfNoteServiceMethods.ByName("CreateTdfNote")),
		connect.WithHandlerOptions(opts...),
	)
	tdfNoteServiceGetTdfNoteHandler := connect.NewUnaryHandler(
		TdfNoteServiceGetTdfNoteProcedure,
		svc.GetTdfNote,
		connect.WithSchema(tdfNoteServiceMethods.ByName("GetTdfNote")),
		connect.WithHandlerOptions(opts...),
	)
	tdfNoteServiceQueryTdfNotesHandler := connect.NewUnaryHandler(
		TdfNoteServiceQueryTdfNotesProcedure,
		svc.QueryTdfNotes,
		connect.WithSchema(tdfNoteServiceMethods.ByName("QueryTdfNotes")),
		connect.WithHandlerOptions(opts...),
	)
	tdfNoteServiceStreamTdfNotesHandler := connect.NewServerStreamHandler(
		TdfNoteServiceStreamTdfNotesProcedure,
		svc.StreamTdfNotes,
		connect.WithSchema(tdfNoteServiceMethods.ByName("StreamTdfNotes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tdf_notes.v1.TdfNoteService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TdfNoteServiceCreateTdfNoteProcedure:
			tdfNoteServiceCreateTdfNoteHandler.ServeHTTP(w, r)
		case TdfNoteServiceGetTdfNoteProcedure:
			tdfNoteServiceGetTdfNoteHandler.ServeHTTP(w, r)
		case TdfNoteServiceQueryTdfNotesProcedure:
			tdfNoteServiceQueryTdfNotesHandler.ServeHTTP(w, r)
		case TdfNoteServiceStreamTdfNotesProcedure:
			tdfNoteServiceStreamTdfNotesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTdfNoteServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTdfNoteServiceHandler struct{}

func (UnimplementedTdfNoteServiceHandler) CreateTdfNote(context.Context, *connect.Request[v1.CreateTdfNoteRequest]) (*connect.Response[v1.CreateTdfNoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tdf_notes.v1.TdfNoteService.CreateTdfNote is not implemented"))
}

func (UnimplementedTdfNoteServiceHandler) GetTdfNote(context.Context, *connect.Request[v1.GetTdfNoteRequest]) (*connect.Response[v1.GetTdfNoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tdf_notes.v1.TdfNoteService.GetTdfNote is not implemented"))
}

func (UnimplementedTdfNoteServiceHandler) QueryTdfNotes(context.Context, *connect.Request[v1.QueryTdfNotesRequest]) (*connect.Response[v1.QueryTdfNotesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tdf_notes.v1.TdfNoteService.QueryTdfNotes is not implemented"))
}

func (UnimplementedTdfNoteServiceHandler) StreamTdfNotes(context.Context, *connect.Request[v1.StreamTdfNotesRequest], *connect.ServerStream[v1.StreamTdfNotesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("tdf_notes.v1.TdfNoteService.StreamTdfNotes is not implemented"))
}
